### PR TITLE
Fix #163 : Pixel Overflow in Bottom Toolbar  

### LINKED ISSUE #163: Pixel Overflow in Bottom Toolbar
### How to reproduce this?
 Just click the camera icon in the floating action buttons. After that when the picture opens up in the app you will see a bottom navigation toolbar.  See the pixels just overflowed in the toolbar.

### Screenshots
Screenshot_2021-03-11-21-09-54-61

### Possible Fix:
Effective use of Media Queries.

### Device
Oppo A31

### PR DESCRIPTION
**Pull request by 0xapurv**
**Changes**

- Bottom Toolbar height increased , previously `h/19`now it is `h/18` using `MediaQuery`.
- `mainAxisAlignment: MainAxisAlignment.spaceEvenly` added in all the used `Column`.

Fixes [#163 ](https://github.com/smaranjitghose/DocLense/issues/163)

> Inspector is now looking good too.

Screenshot_1615549188

### CODE REVIEW

**Comment by 0xapurv** [comment]
hey, @arteevraina kindly take a look into it, any suggestion If I can achieve this in some better way or is it cool?

**Review by arteevraina — APPROVED** [review]
Changes look good to me. But, I think a better approach would have been to use a `Row` and keeping these icons as child widgets and keeping the `mainAxisAlignment` of Row as `spaceEvenly`.

**Comment by 0xapurv** [comment]
> Changes look to me. But, I think a better approach would have been to use a `Row` and keeping these icons as child widgets and keeping the `mainAxisAlignment` of Row as `spaceEvenly`.

Actually, Its already inside a `Row` and `mainAxisAlignment` is set as `spaceEvenly`. So can we go with this approach right?

>Imageview.dart line no 118
Screenshot (1)

**Comment by anushbhatia** [comment]
> > Changes look to me. But, I think a better approach would have been to use a `Row` and keeping these icons as child widgets and keeping the `mainAxisAlignment` of Row as `spaceEvenly`.
> 
> Actually, Its already inside a `Row` and `mainAxisAlignment` is set as `spaceEvenly`. So can we go with this approach right?
> 
> > Imageview.dart line no 118
> > Screenshot (1)

Its fine to me as of now. Reslove the conflict @believeInJha . @smaranjitghose or @arteevraina then they will merge it

**Comment by arteevraina** [comment]
> > Changes look to me. But, I think a better approach would have been to use a `Row` and keeping these icons as child widgets and keeping the `mainAxisAlignment` of Row as `spaceEvenly`.
> 
> Actually, Its already inside a `Row` and `mainAxisAlignment` is set as `spaceEvenly`. So can we go with this approach right?
> 
> > Imageview.dart line no 118
> > Screenshot (1)

Cool then ! Resolve the conflicts and I will merge it then.

**Pull request merged**
