### PR TITLE
Fixed the issue with app crashing on pressing the crop button

### LINKED ISSUE #88: App Crash: Pressing the crop button makes the app crash
Using the crop feature makes the app crash both on my emulator and my physical device. The cause for this is some missing lines in ```AndroidManifest.xml```. 

After adding the code, the app works perfect but if I initially choose to crop, but then go back from the crop screen without cropping the image, it gives me an error saying the imagefile is null. This is solved by giving a minor tweek to ```cropimage``` function.

Edit: I have made the crop screen consistent with the present theme, I'll open a PR.

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Closes #88 

The crop button works now and there is no issue or error when a user returns from the crop screen without cropping the image. Please review.

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/40017559/107606013-cd2bfa80-6c5a-11eb-818a-90f3da228d36.mp4

Resolve this image stretch as soon as we crop the image

**Comment by Saransh-cpp** [comment]
I'll do the necessary changes but do you have any idea why this PR isn't showing any conflict? I fixed this particular issue in the #93 PR as this was an issue which was applicable to the whole Imageview.dart file.

**Comment by Saransh-cpp** [comment]
Okay after a push it shows conflicts, I'll fix them.

**Comment by anushbhatia** [comment]
Sure

**Comment by Saransh-cpp** [comment]
I think the issue has been solved now, the problem was the same ```fit: BoxFit.fill``` line.

**Pull request merged**
