### PR TITLE
fix(Whole Project): renamed files.

### LINKED ISSUE #160: File names are not according to Dart preferences.
The source code file names are not according to Dart Preferences. And There is a lot of redundant code and imports. Can I fix them ?'
I am a participant of GSSOC 21

### PR DESCRIPTION
**Pull request by SapinderSingh**
Renamed all files and fixed imports according to Dart Preferences.

fixes #160

### CODE REVIEW

**Comment by SapinderSingh** [comment]
@arteevraina Finally did it. Please check this now.

**Comment by Saransh-cpp** [comment]
There are a lot of small mistakes in this PR which will make the whole app stop working. 
For ex - Instead of 
```dart
import package:doclense/providers/theme_provider.dart
``` 
some files have the import 
```dart
import package:doclense/Providers/theme_provider.dart
```
Please ensure they are fixed.

**Comment by SapinderSingh** [comment]
> There are a lot of small mistakes in this PR which will make the whole app stop working.
> For ex - Instead of
> 
> ```dart
> import package:doclense/providers/theme_provider.dart
> ```
> 
> some files have the import
> 
> ```dart
> import package:doclense/Providers/theme_provider.dart
> ```
> 
> Please ensure they are fixed.

Then what should be my next step? I have to delete this PR and add a new one ?

**Comment by SapinderSingh** [comment]
> There are a lot of small mistakes in this PR which will make the whole app stop working.
> For ex - Instead of
> 
> ```dart
> import package:doclense/providers/theme_provider.dart
> ```
> 
> some files have the import
> 
> ```dart
> import package:doclense/Providers/theme_provider.dart
> ```
> 
> Please ensure they are fixed.

and can you tell me, why vs code and android studio are ignoring this?

**Comment by Saransh-cpp** [comment]
> > There are a lot of small mistakes in this PR which will make the whole app stop working.
> > For ex - Instead of
> > ```dart
> > import package:doclense/providers/theme_provider.dart
> > ```
> > 
> > 
> > some files have the import
> > ```dart
> > import package:doclense/Providers/theme_provider.dart
> > ```
> > 
> > 
> > Please ensure they are fixed.
> 
> Then what should be my next step? I have to delete this PR and add a new one ?

No, you can fix these mistakes, commit the changes and push them and the new changes will automatically be reflected here. Please make sure to run the app first and push only when the app runs successfully. You can also have a look on all the issues by clicking `details` on the failed lint tests so that it becomes easier for you to locate and fix them.

**Comment by SapinderSingh** [comment]
@Saransh-cpp Please check

**Comment by Saransh-cpp** [comment]
> @Saransh-cpp Please check

Great, all the imports and file names are fixed. I can't give the final judgement, you can request any of the mentors to do that! (you need to fix the conflicts though)

**Pull request closed without merging**
