### PR TITLE
Added image preview to PDF card in home screen

### LINKED ISSUE #99: Improving the style of displaying the pdf's in home page
Currently, there are represented just by a white card with its name on it we add multiple features to it.
Design and features of it are listed below check them and also you can implement each feature at a time.

### LINKED ISSUE #193: Adding a preview on home page
Currently, there's no preview of pdf on the home page.
Add a small preview of the image there. Instead of the image icon present there.
Screenshot_20210317_012454

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Closes #193 
Hopefully finally Closes #99 

## Changes
1. The preview photo is added in the Hive box in a similar fashion as the date is added.
2. All the storage style changes have been discussed in #169, and this PR uses that change of storage style to incorporate the storing of image too.

## Screenshots
<p float="left">

</p>

Please let me know if you want any changes in this PR, thanks!

(CWoC and GSSoC participant)

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Screenshot_20210318_032728_com example doclense

**Comment by Saransh-cpp** [comment]
@anushbhatia was this error faced on starting up the app or after you created a PDF and opened the home screen?

**Comment by anushbhatia** [comment]
> @anushbhatia was this error faced on starting up the app or after you created a PDF and opened the home screen?

startup on the home screen

**Comment by Saransh-cpp** [comment]
> > @anushbhatia was this error faced on starting up the app or after you created a PDF and opened the home screen?
> 
> startup on the home screen

This might be because you already have some PDFs in your app/Hive box which do not have a preview image as they were created before this code was written. Can you please once uninstall the app from your device then install it using the code from this branch and then let me know if this error still pops up?

**Comment by anushbhatia** [comment]
> > > @anushbhatia was this error faced on starting up the app or after you created a PDF and opened the home screen?
> > 
> > 
> > startup on the home screen
> 
> This might be because you already have some PDFs in your app/Hive box which do not have a preview image as they were created before this code was written. Can you please once uninstall the app from your device then install it using the code from this branch and then let me know if this error still pops up?

🙌Sure let me check that.

**Comment by anushbhatia** [comment]
Screenshot_20210318_155537_com example doclense
Overflow of icons

**Comment by Saransh-cpp** [comment]
@anushbhatia please check now

**Comment by Saransh-cpp** [comment]
Should I also fix the pixel overflow in imageview and filterview screens or is someone working on that?

**Comment by anushbhatia** [comment]
> Should I also fix the pixel overflow in imageview and filterview screens or is someone working on that?

Nobody is working you can raise the pr.

**Comment by Saransh-cpp** [comment]
@anushbhatia could you please add the CrossWOC and the level labels on this PR

**Pull request merged**
