### PR TITLE
Implemented dark theme

### LINKED ISSUE #74: Feature: Implementing theme change option
This feature right now is not working in the app. I'd like to work on it as a part of MWoC and I was thinking of just giving the user a switch, to switch between 2 themes rather than a dropdown menu which is present in the app right now. Please give your inputs so I can start working on this. Thank you.

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Closes #74 

Settings page now offers a switch which can be used to turn on the dark mode.

A big PR, please merge this before merging other PRs as resolving conflicts in this would be very difficult. Please let me know if any changes required. Thank you so much!

And please let me know how will my scores be updated or reflected on the MWoC's official leaderboard which is present on their site.

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Added new logos in the assets folder which can be added to the dark mode of the page and also add dark mode to the review page too

**Comment by Saransh-cpp** [comment]
> Added new logos in the assets folder which can be added to the dark mode of the page and also add dark mode to the review page too

Is the rating dialogue and the review page same? or else can you please provide me with the path for the page, I can't locate it.

**Comment by anushbhatia** [comment]
Yes they are same

**Comment by Saransh-cpp** [comment]
Rating dialogue actually has only a single colour property which is accent colour. I have already applied that to be dynamic but I can't find the complete box's colour property.

Edit: Don't merge yet, I will have to take some suggestions for the icons. I will do that tomorrow morning.

**Comment by anushbhatia** [comment]
Sure no problem

**Comment by Saransh-cpp** [comment]
## The review dialogue, please let me know if you want any changes.

Screenshot_1612858672
Screenshot_1612858689

## The logo in About.dart, please let me know if you want any changes.

Screenshot_1612858684
Screenshot_1612858675

**Comment by Saransh-cpp** [comment]
Please let me know if there are any further changes you want. Thank you.

**Pull request merged**
