### PR TITLE
Added delete, rename and move functionalities

### PR DESCRIPTION
**Pull request by nathsagar24**

### CODE REVIEW

**Comment by anushbhatia** [comment]
Which program are you part of?

**Review by anushbhatia — APPROVED** [review]

**Comment by nathsagar24** [comment]
> Which program are you part of?

I am part of CrossWoC

**Comment by anushbhatia** [comment]
Great work @nathsagar24 Keep it up feel free to raise more issues and contribute to open source

**Comment by nathsagar24** [comment]
Sure

**Comment by nathsagar24** [comment]
Hey can you add points to the issue for CrossWoc leaderboard?

**Comment by smaranjitghose** [comment]
> Hey can you add points to the issue for CrossWoc leaderboard?

1 week before the CWOC deadline could you tag both of us in the main channel.  So that we can directly communicate the updated points

**Comment by nathsagar24** [comment]
> > Hey can you add points to the issue for CrossWoc leaderboard?
> 
> 1 week before the CWOC deadline could you tag both of us in the main channel.  So that we can directly communicate the updated points

Its the last week actually. I will tag you.

**Comment by smaranjitghose** [comment]
> > > Hey can you add points to the issue for CrossWoc leaderboard?
> > 
> > 
> > 1 week before the CWOC deadline could you tag both of us in the main channel.  So that we can directly communicate the updated points
> 
> Its the last week actually. I will tag you.

Sure.

**Pull request merged**
