### PR TITLE
fix(Whole Project): Renamed files and folders. fixed #160

### LINKED ISSUE #160: File names are not according to Dart preferences.
The source code file names are not according to Dart Preferences. And There is a lot of redundant code and imports. Can I fix them ?'
I am a participant of GSSOC 21

### PR DESCRIPTION
**Pull request by SapinderSingh**
Renamed all files and folders according to Dart preferences.

fixes #160

Note: No lines of code were deleted or added. The additions and deletions that you are seeing is a reformat performed by vs code automatically, when we save the file.

### CODE REVIEW

**Comment by Saransh-cpp** [comment]
@SapinderSingh this PR is filled with errors because of which lint checks are failing in other PRs. For example - You haven't renamed `Services` to `services` but you have changed all the imports.

Import in home screen - 
image

Directory name - 
image

There are a lot of mistakes like this. I will fix them in one of my PR but please make sure that next time such mistakes don't happen.

**Comment by Saransh-cpp** [comment]
@anushbhatia is there any way that we can "un-merge" this PR?
[Here](https://github.com/smaranjitghose/DocLense/pull/243/checks?check_run_id=2221326692) are all the failing checks which came up when I pulled the latest code (which had code from this PR) in one of my PRs 
image

The failing checks are huge in number, I don't know why lint checks passed on this PR but it is a huge mess and fixing this would take a lot of time

**Comment by Saransh-cpp** [comment]
> @anushbhatia is there any way that we can "un-merge" this PR?
> [Here](https://github.com/smaranjitghose/DocLense/pull/243/checks?check_run_id=2221326692) are all the failing checks which came up when I pulled the latest code (which had code from this PR) in one of my PRs
> image
> 
> The failing checks are huge in number, I don't know why lint checks passed on this PR but it is a huge mess and fixing this would take a lot of time

Fixed them in #243

**Comment by SapinderSingh** [comment]
> @SapinderSingh this PR is filled with errors because of which lint checks are failing in other PRs. For example - You haven't renamed `Services` to `services` but you have changed all the imports.
> 
> Import in home screen - 
> image
> 
> Directory name - 
> image
> 
> There are a lot of mistakes like this. I will fix them in one of my PR but please make sure that next time such mistakes don't happen.
> 
> 

Thanks for help. I will take care, next time.

**Comment by SapinderSingh** [comment]
image_2021-03-30_044954
@Saransh-cpp, I did the work properly, you can see the screenshot. I don't know, why these errors are showing on your system. BTW Thank You so much for your help.

**Pull request merged**
