### PR TITLE
Implement search

### PR DESCRIPTION
**Pull request by Vrushti24**
Implemented search_feature

### CODE REVIEW

**Review by anushbhatia — COMMENTED** [review]
https://user-images.githubusercontent.com/40017559/105689646-05c09a00-5f21-11eb-8e7b-ab1ac3ee79b0.mp4

Not working

**Comment by Vrushti24** [comment]
I don't know what would be the issue it was working early now I don't know
suddenly what happened.😟

**Comment by anushbhatia** [comment]
check and seee if you can resolve this problem

**Comment by Vrushti24** [comment]
I will try but thank u for every time helping and not getting exausted
thank u really appreciate it

**Comment by anushbhatia** [comment]
Anytime we are here for that

**Comment by smaranjitghose** [comment]
Fix the merge conflicts by incorporating the changes please

**Comment by Vrushti24** [comment]
Conflicts were also solved

**Comment by Vrushti24** [comment]
They are showing no conflict

**Pull request closed without merging**
