### PR TITLE
Fixed renderflex overflow in the bottom nav bar

### LINKED ISSUE #178: Bottomoverflow error
### After taking a picture it is showing the bottom overflow error 
Screenshot_2021-03-14-20-20-35-69

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Closes #178 

## Screenshots

1. Pixel 2

2. Redmi note 5 pro

Please let me know if you want any changes in this PR, thanks!

(CWoC and GSSoC participant)

### CODE REVIEW

**Comment by anushbhatia** [comment]
Would it better to you safe area rather than this?

**Comment by Saransh-cpp** [comment]
> Would it better to you safe are rather than this?

I'll check and let you know

**Comment by anushbhatia** [comment]
any update?

**Comment by Saransh-cpp** [comment]
> any update?

Yes, putting the expanded widget in safe area gives the below error on console, the safe area was removed in #75 because of this error.

image

**Comment by Saransh-cpp** [comment]
@anushbhatia please add the respective CrossWOC labels

**Pull request merged**
