### PR TITLE
settings : contact developers screen

### LINKED ISSUE #190: Settings Page: Contact Developers
Add an action to show the LinkedIn and GitHub profiles along with photos of
Smaranjit and Anush in the section
https://github.com/smaranjitghose/girlscript_app refer to the team page present here. 
Screenshot_20210317_005612
 

On click you can open a new page and add those features there.

### PR DESCRIPTION
**Pull request by nicks101**
fixes #190 

- Added profiles of developers (smaranjit and anush).
- Profile includes image, name, GitHub and linked links.

#### Dark Mode

Screenshot_1616138872

#### Light Mode

Screenshot_1616138881

### CODE REVIEW

**Comment by anushbhatia** [comment]
Make those images circular with some box shadow run the refrence app in the issue and you can take the UI from that too.

**Comment by nicks101** [comment]
What about this?


Screenshot_1616315438

**Comment by anushbhatia** [comment]
Align image of smaranjit in center

**Comment by nicks101** [comment]
Screenshot_1616400235

**Pull request merged**
