### PR TITLE
Camera Modified.... Now App Not Crash after taking Image

### PR DESCRIPTION
**Pull request by SamarpanCoder2002**
I modified the camera.... Now App will not crash after taking image

issue: #210 

Due to some problem, I made this pull request from another branch..... This is the extended of pull request #227 

Video demo: https://drive.google.com/file/d/1T6dmU7OkKsK13mwmkrihYFoYP97kX5Jb/view?usp=sharing

@anushbhatia hope you review it and merge it

### CODE REVIEW

**Comment by SamarpanCoder2002** [comment]
I don't know why that lint fail.... I not made any changes in `starred_documents.dart` file, but it shows issues in that file.... After fetch from upstream, that problem happen..... I am not responsible for that..... 

Hope you review it and merge it @anushbhatia

**Comment by SamarpanCoder2002** [comment]
@anushbhatia Now it's totally works fine and camera view modified and bugs fixed.... I also attach a video demo link... Kindly review it and merge it... I am also a GSSOC'21 participant... Thanks @anushbhatia

**Comment by SamarpanCoder2002** [comment]
All conflicts are resolved and all lint are passed... Wish that, hope you review it and merge it soon @anushbhatia

**Comment by smaranjitghose** [comment]
@SamarpanCoder2002 Please do a squash commit

**Comment by SamarpanCoder2002** [comment]
> @SamarpanCoder2002 Please do a squash commit

ok....and thanks for merge

**Pull request merged**
