### PR TITLE
Fixed Issue 160

### PR DESCRIPTION
**Pull request by SapinderSingh**
Renamed all the files according to Dart Preferences and guidelines. Also fixed the imports as suggested.

### CODE REVIEW

**Comment by arteevraina** [comment]
Hey, @SapinderSingh Please resolve the merge conflicts.

**Comment by SapinderSingh** [comment]
@arteevraina can you guide me ?

**Comment by SapinderSingh** [comment]
> Hey, @SapinderSingh Please resolve the merge conflicts.

What should I do to resolve merge conflicts?

**Comment by arteevraina** [comment]
> > Hey, @SapinderSingh Please resolve the merge conflicts.
> 
> What should I do to resolve merge conflicts?

Check out your feature branch and pull the latest changes from upstream. Then your code editor will give you suggestion, whether you want to keep your change or accept incoming change. This way proceed step by step and then test the app before pushing your code. If this works then you are good to go :)

**Comment by arteevraina** [comment]
Still if you get stuck just ping here or on the channel. I will try to help.

**Pull request closed without merging**
