### PR TITLE
Renamed all files and folders according to Dart Preferences.

### PR DESCRIPTION
**Pull request by SapinderSingh**
I have renamed all the files and folders according to dart preferences. And reformatted the lib/starred_documents.dart file.

### CODE REVIEW

**Review by arteevraina — APPROVED** [review]
Are there any other files left that need to follow the dart preferences guidelines?

**Comment by SapinderSingh** [comment]
> 
> 
> Are there any other files left that need to follow the dart preferences guidelines?

No Sir

**Comment by anushbhatia** [comment]
Renaming these files also modify all the imports to the corresponding calls in all places so that it won't create an error currently it has lots of errors regarding this. Do check them

**Comment by anushbhatia** [comment]
Create a new pr for this.

**Comment by SapinderSingh** [comment]
> 
> 
> Create a new pr for this.

Okay

**Pull request closed without merging**
