### PR TITLE
Implement_search

### PR DESCRIPTION
**Pull request by Vrushti24**

### CODE REVIEW

**Comment by smaranjitghose** [comment]
@Vrushti24 Please do a SQUASH commit from next time

**Comment by smaranjitghose** [comment]
Also, your pubsec.yaml has dependency errors

**Comment by Vrushti24** [comment]
Okay I will change again

**Review by anushbhatia — CHANGES_REQUESTED** [review]
pubspec.yaml is having errors rectify them once

**Comment by Vrushti24** [comment]
Hey @smaranjitghose/DocLense <DocLense@noreply.github.com>  I have tried a
lot but couldn't rectify the errors it's been long time I am doing this but
not able to complete what should I do now ?

**Comment by anushbhatia** [comment]
Sure will look into this and try resolving these errors and rectify these errors otherwise take the latest repo and add these changes to it.

**Comment by Vrushti24** [comment]
I have to make a PR again since I m not able to solve the issue ?? Will I
get some points or not ???

**Comment by anushbhatia** [comment]
Simply make a fresh PR taking the latest repo and then add the code of search bar in it. This won't create any errors

**Comment by Vrushti24** [comment]
Ok, will do that. Thank u

**Pull request closed without merging**
