### PR TITLE
Feature/full length image pdf

### PR DESCRIPTION
**Pull request by Niteshkr123**
On selecting any image either from the gallery or camera, the user will now see the full-screen image in it.

### CODE REVIEW

**Comment by Niteshkr123** [comment]
Screenshot_2021-02-04-12-07-07-83_7294a262473530cafd6e94bd645d3149

**Comment by smaranjitghose** [comment]
@Niteshkr123 All of your PRs are having the same issue due to commit history conflict

There are two ways to fix this,

# 1 The usual way:

- Fetch the changes from this repo (upstream) to your repo(forked). We are concerned with main branch as of now
- Create a new feature branch from the updated main branch
- Do your changes
- Give the PR (or update the same one with a SQUASH Commit)

#2 The  weird yet fast way:

- Delete your forked copy of the repo
- Fork this repo again
- Clone it
- Do the changes
- Raise a PR

** for all your PRs, the deletion of ``vscode\`` in the commit history is resulting in the merge conflicts

**Comment by Niteshkr123** [comment]
okay, sir, will go with the second way, please allow me some time to do all
that code again. That will take few days for me.

**Comment by anushbhatia** [comment]
Resolve these dependeincies

**Pull request closed without merging**
