### PR TITLE
Settings page created

### PR DESCRIPTION
**Pull request by himanshu007-creator**

### CODE REVIEW

**Comment by smaranjitghose** [comment]
Please spend some time in the PR.
- The logo unfortunately doesn't meet our minimum requirements.
- Please use Adobe XD or figma to design them.
- I was curious about the HTML, css code.
- Whenever you give a PR, please attach screenshots of the work
- And we intend this to be an open source app, so file names like "himanshu logo" are not suitable.

I hope you understand @himanshu007-creator

**Comment by himanshu007-creator** [comment]
> Please spend some time in the PR.
> 
> * The logo unfortunately doesn't meet our minimum requirements.
> * Please use Adobe XD or figma to design them.
> * I was curious about the HTML, css code.
> * Whenever you give a PR, please attach screenshots of the work
> * And we intend this to be an open source app, so file names like "himanshu logo" are not suitable.
> 
> I hope you understand @himanshu007-creator

yes sir, i will rename the file for sure :+1: 
but can you elaborate me more on the issue of logos?
i will work on it once you give me more specific guidelines for it.

**Comment by himanshu007-creator** [comment]
HI @smaranjitghose sir,
i have improved the settings page. 
1) Changed the icons as adviced, 
2) changed the logo name from <code>himanshu logo"</code> to <code>doclens logo1</code>
3) added a favicon for the webpage.
please review it :+1:

**Comment by smaranjitghose** [comment]
As I pointed out earlier, this is a flutter application and there is no need of HTML, css code as of now. Please go through the codebase carefully before taking up an issue

**Pull request closed without merging**
