### PR TITLE
Fixed the delete button

### LINKED ISSUE #139: The delete PDF option improvements
1. The delete button does not provide a warning of any sort to the user before deleting the PDF.
2. PDFs from the ```starred``` box are not deleted, they should be deleted when the original PDF is deleted.

I would like to work on this issue.

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Closes #139 

## Changes
1. Added logic for removing the PDF from both the boxes (```pdf``` and ```starred```) together, once the user clicks the delete button.
2. Added a confirmation dialogue box for the delete option.

The major changes are from line 215 to line 299 in Home.dart.

Please let me know if any changes are required. Thanks!

(MWoC and CWoC participant)

### CODE REVIEW

**Review by smaranjitghose — APPROVED** [review]

**Comment by smaranjitghose** [comment]
@Saransh-cpp could you please compare your score on the MWOC leaderboard and your PRs to this repo, therby letting us know of any discrepencies

**Comment by Saransh-cpp** [comment]
> @Saransh-cpp could you please compare your score on the MWOC leaderboard and your PRs to this repo, therby letting us know of any discrepencies

3 of my PRs which were merged yesterday are not being reflected on the leaderboard. PR - #132 , #134 and #137 . The labels were added but the workflow didn't work. The score for this PR was reflected so I guess the workflow is working fine now, please communicate with the organizers for those 3 PRs.

**Comment by smaranjitghose** [comment]
> > @Saransh-cpp could you please compare your score on the MWOC leaderboard and your PRs to this repo, therby letting us know of any discrepencies
> 
> 3 of my PRs which were merged yesterday are not being reflected on the leaderboard. PR - #132 , #134 and #137 . The labels were added but the workflow didn't work. The score for this PR was reflected so I guess the workflow is working fine now, please communicate with the organizers for those 3 PRs.

I'll definitely forward this to the orgainzers. 
Could you please let me know the total no PRs merged for you(w.r.t this project) and total score as of now

**Comment by Saransh-cpp** [comment]
Yes sure, 27 merged, 2 open. Score as of now on the leaderboard is 1125, the score should be 1125+225 that is 1350. 225 is the score for those 3 PRs (+100+100+25)

**Comment by Saransh-cpp** [comment]
@smaranjitghose this PR also does not contain the CrossWOC and difficulty labels. This is the last one for CrossWOC.

**Pull request merged**
