### PR TITLE
Feature/app rating

### PR DESCRIPTION
**Pull request by Niteshkr123**
Added a feature through which users can rate DocLense. Whenever the user will exit from the app, a popup will appear for rating DocLense.

### CODE REVIEW

**Comment by Niteshkr123** [comment]
Screenshot_2021-02-01-17-59-00-49_7294a262473530cafd6e94bd645d3149

**Comment by Niteshkr123** [comment]
Screenshot_2021-02-01-17-59-07-03_7294a262473530cafd6e94bd645d3149

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Redirect to playstore when you submit the rating and add this feature in the main drawer. Dart file so that everyone can see it.

**Comment by Niteshkr123** [comment]
I have moved the rating feature to the drawer. Users can now rate DocLense. On clicking on submit button they will be redirected to the play store. ( Please note: I haven't used the play store link there, just for demo purposes I have used the GitHub repo link, once it will get uploaded on the play store we can replace that link with the app link).

Kindly review this PR.

**Comment by Niteshkr123** [comment]
Screenshot_2021-02-03-15-27-14-90_7294a262473530cafd6e94bd645d3149

**Comment by smaranjitghose** [comment]
@Niteshkr123 Can you please close this PR and give it again. Since I have removed the ``.vscode/`` and .gitignore it. We would have some merge conflicts

**Pull request closed without merging**
