### PR TITLE
Feature/image preview bug

### PR DESCRIPTION
**Pull request by Niteshkr123**
Removed the bug in the image preview section. Pixel overflow condition has been removed.

### CODE REVIEW

**Comment by Niteshkr123** [comment]
Screenshot_2021-02-03-17-33-43-24_7294a262473530cafd6e94bd645d3149

**Comment by Niteshkr123** [comment]
Screenshot_2021-02-03-17-43-21-42_7294a262473530cafd6e94bd645d3149

**Comment by smaranjitghose** [comment]
Same .vscode issue. Please give this PR again

**Comment by Niteshkr123** [comment]
I have made a new commit on the image preview bug. Please have a look.

**Comment by anushbhatia** [comment]
Resolve this and give a new PR

**Pull request closed without merging**
