### PR TITLE
Change the all icons color in home.dart

### PR DESCRIPTION
**Pull request by Neha62-lit**
1.Change the icons color.
2.Add a box-shadow to card.
3.Change the card color to white.

home_docLense

### CODE REVIEW

**Comment by Neha62-lit** [comment]
@smaranjitghose Please review and merge this PR.

**Comment by Neha62-lit** [comment]
@anushbhatia @smaranjitghose I renamed all file names to lowercase_with_underscore, because I'm getting some errors and according to Lint rules, all file names should be in lowercase. So I did it.
Please review and merge this PR.

**Review by arteevraina — APPROVED** [review]
Looks Good!

**Comment by arteevraina** [comment]
Hey @Neha62-lit ! You will need to resolve conflicts after that it can be merged.

**Comment by Neha62-lit** [comment]
> Hey @Neha62-lit ! You will need to resolve conflicts after that it can be merged.

Okay!

**Comment by Neha62-lit** [comment]
@smaranjitghose I am unable to resolve these conflicts. Please help me resolving those.

**Comment by anushbhatia** [comment]
https://www.youtube.com/watch?v=iRyUUGsNHrU use this. Also, you can refer to the documentation for this or else you can create a new PR.

**Comment by Neha62-lit** [comment]
> https://www.youtube.com/watch?v=iRyUUGsNHrU use this. Also, you can refer to the documentation for this or else you can create a new PR.

Okay..

**Pull request closed without merging**
