### PR TITLE
Image Measuring Handles

### LINKED ISSUE #209: Implementing measuring handles
Adding a feature to add dynamic cropping box explained in this [repo]https://github.com/doo/scanbot-sdk-example-flutter)
image
Adding measuring handles in the project to get better output.

### PR DESCRIPTION
**Pull request by nicks101**
Fixes #209 

- Draggable image handles to crop the image with the selected area during image selection for pdf.
- Using [opencv](https://opencv.org/) package in android. Result is displayed in flutter app using [method channel](https://flutter.dev/docs/development/platform-integration/platform-channels).
- Only implemented for android devices.

Screenshot_1617961428

Screenshot_1617961434

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
Screenshot_20210414_123828_com example doclense

It doesn't form the bounding box around tge image. Might be due to deprecated files present there.

**Comment by nicks101** [comment]
> It doesn't form the bounding box around tge image. Might be due to deprecated files present there.

I just ran the app on this branch, it works fine. The bounding box comes at the border ( -20 px) of the image.
Can you suggest how shall we debug this?

This is how border comes initially.

Screenshot_1618485766

**Comment by anushbhatia** [comment]
But why then it shows me this kind of the image

**Comment by anushbhatia** [comment]
But I tried with many different pictures.

**Pull request merged**
