### PR TITLE
appRatingAdded

### PR DESCRIPTION
**Pull request by Niteshkr123**
Added a feature through which user can now rate Doclence

### CODE REVIEW

**Comment by Niteshkr123** [comment]
Screenshot_2021-02-06-11-12-33-87_7294a262473530cafd6e94bd645d3149
Screenshot_2021-02-06-11-12-43-47_7294a262473530cafd6e94bd645d3149

**Comment by Niteshkr123** [comment]
Sir please add tag of DWOC and level tag too.

**Comment by smaranjitghose** [comment]
> Sir please add tag of DWOC and level tag too.

You are just in DWOC right @Niteshkr123 or any other program too?

**Comment by Niteshkr123** [comment]
Sir I have filled my application for Girl script summer of code ,but their program will start in 1st march

**Pull request merged**
