### PR TITLE
Redesigned Main Drawer

### LINKED ISSUE #84: Redesign App Drawer
Following the Colour Codes given in the readme.
Adding relevant icons to denote the particular section if you want.

### PR DESCRIPTION
**Pull request by Saransh-cpp**
Closes #84 

Shuffled the list tiles to their right position and added dividers between different sections. The color of the dividers change dynamically.

### CODE REVIEW

**Review by anushbhatia — CHANGES_REQUESTED** [review]
image
Resolve the overflow also one minor change on the splash screen use the white logo for it.

**Comment by Saransh-cpp** [comment]
I made all the logo changes in the previous PR. I have no idea why the PRs are not giving any conflicts. I will try to push the change fixing the overflow issue and if I don't get the conflict issues then I will fix the issues in the following commits.

**Comment by Saransh-cpp** [comment]
I got the conflicts after one push and I solved them. Please let me know if you want any more changes!

**Comment by anushbhatia** [comment]
Remove the share the pdf option as of now

**Comment by Saransh-cpp** [comment]
@smaranjitghose the second one

**Pull request merged**
